# Generated by Django 6.0.1 on 2026-01-23 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statuses', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='status',
            old_name='timestamp',
            new_name='created_at',
        ),
    ]
